# Generated by Django 6.0.6 on 2026-06-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, help_text="Internal campaign note (e.g. 'Black Friday')", max_length=200),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_free_shipping',
            field=models.BooleanField(default=False, help_text='Waive all shipping fees if applied.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='Max times this coupon can be used. 0 means unlimited.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
