# Generated by Django 6.0.6 on 2026-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_populate_product_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Summer Influencer Batch', max_length=100)),
                ('prefix', models.CharField(help_text='e.g. SUM for SUM-XXXXX', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=100, help_text='How many codes to generate')),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Black Friday Cyber Sale', max_length=200)),
                ('discount_percentage', models.PositiveIntegerField(help_text='e.g. 15 for 15% off')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='flash_sales', to='shop.category')),
                ('specific_products', models.ManyToManyField(blank=True, related_name='flash_sales', to='shop.product')),
            ],
        ),
    ]
