# Generated by Django 6.0.6 on 2026-06-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for the banner', max_length=200)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d')),
                ('link', models.URLField(blank=True, help_text='Optional URL to redirect when clicked')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which banners are displayed (lowest first)')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
