# Generated by Django 6.0.6 on 2026-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brands/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='categories', to='shop.brand'),
        ),
    ]
