# Generated by Django 6.0.6 on 2026-07-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_review'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'is_featured'], name='shop_produc_availab_30a8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'category'], name='shop_produc_availab_16d7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'brand'], name='shop_produc_availab_5d8380_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='shop_produc_created_661b12_idx'),
        ),
    ]
