# Generated by Django 6.0.6 on 2026-07-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_shop_produc_id_f21274_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. RAM, CPU, Storage, Battery', max_length=100)),
                ('value', models.CharField(help_text='e.g. 16 GB DDR5, Intel i7-13700H', max_length=200)),
                ('numeric_value', models.FloatField(blank=True, help_text='Numeric value for comparison, e.g. 16 for 16GB', null=True)),
                ('unit', models.CharField(blank=True, help_text='e.g. GB, GHz, mAh, hrs', max_length=50)),
                ('icon', models.CharField(blank=True, default='⚡', help_text='Emoji or icon code', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='shop.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
