# Generated by Django 6.0.6 on 2026-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_populate_product_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Text of the announcement', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide this announcement')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which announcements appear')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['order', 'id'],
            },
        ),
    ]
