# Generated by Django 6.0.6 on 2026-06-21 11:30

from django.db import migrations


def link_users(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    User = apps.get_model('auth', 'User')
    for order in Order.objects.filter(user__isnull=True):
        user = User.objects.filter(email=order.email).first()
        if user:
            order.user = user
            order.save()

def reverse_link(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.RunPython(link_users, reverse_link),
    ]
